### ISSUE TITLE
Fix OpenJFK issues to support developing against GeneiousPrime

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#116]
Currently, Geneious Prime (2019.1.1) requires Java 11 and Java 11 does not contain OpenJFK.
I tried installing JFK libraries through gradle but could not get a working configuration to recognize them.
This issue highlights the need to get this working again.  Meanwhile, i am developing the plugin using
Java 10 and Geneious v 11.1.5

**Comment by matthew-cheung** [comment]
@jdeck88 it sounds like you might have been trying to run with an earlier version of Geneious.  Support for Java 11 was added in 2019.0 so you shouldn't get any messages about missing JavaFX classes from that version or later.  Could you double check **geneiousPublicAPIVersion** in **build.gradle**.  

If you were using 2019.0 or later, were you running via the Gradle runner or via the IntelliJ runner?

**Comment by jdeck88** [comment]
I was able to fix this in the latest plugin release.... not sure of the exact issue here, but it is running now.
