### ISSUE TITLE
LIMS detail view/ Delay

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#126]
When viewing the detail of a record there is slowness.  Note this is different than slowness fetching records from LIMS. 
To recreate the issue: 
XXX fill in details

**Comment by steierj** [comment]
To recreate:
1. search for "FY18_SuriFish_P12" in Plates in Biocode LIMS.
2. this will bring up 24 plates (will take a long time to bring up results - but this is a different issue)
3. click on the first plate that appears in the search results. There will be an up-to-30 second delay on the plate view appearing in the Document Viewer in Geneious and user cannot click anywhere else while the plate view is being brought up.

**Comment by jdeck88** [comment]
I tried recreating this issue on a Macbook Air M1 with 16GB RAM with Geneious 11.1.5 and i had a delay of only 1-2 seconds when clicking on individual plates.  What is the version of geneious and specs on your computer that you are using?

**Comment by jdeck88** [comment]
NOTE: this should not be run in restricted mode in plugin development since it is not fetching traces...

**Comment by jdeck88** [comment]
i spent several hours reearching this issue and it appears that the plugin itself may not have so much control over the operations in displaying a particular document.. this is relegated to geneious itself which will render the document with various available views ... the views themselves that are slow to load have several different types of viewers, for example:
```
12:45:33.787 WARNING: took 197 milliseconds to initialise DocumentViewerFactory =Plate. Generally, these should return quickly and do all the work when first painted.   at com.biomatters.iseek.gui.ViewersPanel.(ViewersPanel.java:655)
12:45:38.248 WARNING: took 4437 milliseconds to initialise DocumentViewerFactory =Tabular Plate View. Generally, these should return quickly and do all the work when first painted.   at com.biomatters.iseek.gui.ViewersPanel.(ViewersPanel.java:655)
12:45:45.418 WARNING: took 7163 milliseconds to initialise DocumentViewerFactory =Sequencing Primers. Generally, these should return quickly and do all the work when first painted.   at com.biomatters.iseek.gui.ViewersPanel.(ViewersPanel.java:655)
```

The very simple plate viewer is quick to load.  i tried several methods to isolate the plate viewer and at least show that first.  I was able to set the precedence of loading so it works on this view first, but it does not prevent the rest of the viewers from loading and locking up the screen.

**Comment by jdeck88** [comment]
After conferring with Matthew from Biomatters and Chris Meyer, we realized the number of metadata fields in GEOME as a whole, greatly impacts the detail view responsiveness.  Additions to the overall GEOME metadata fields in the past two years have led to slowness in the plugin.  The plugin checks the GEOME configuration as a whole to arrange all possible metadata fields BEFORE any queries are run, populating this list when the user first logs into the LIMS/FIMS.   This approach enables users to construct metadata queries across a range of projects before any data is sent back to LIMS and ensures consistency across searches and responses no matter which project data is sent back to the plugin.  

In order to solve this issue and work within the overall assumptions of the plugin, I chose to filter the entire set of metadata fields against a smaller set of metadata fields that is broad enough to cover generalized query needs of field metadata populated in the LIMS, while keeping the number of properties narrow enough to ensure responsiveness in the detail view.   The following list is the 85 fields i chose (down from 200 fields): 
```
String[] arrayFields = {
                    "urn:eventID", "urn:principalInvestigator", "urn:samplingProtocol", "urn:sampleCollectionDevicee", 
                    "urn:recordedBy", "urn:continentOcean", "urn:country", "urn:county", "urn:dayCollected",
                    "urn:decimalLatitude", "urn:decimalLongitude", "urn:enteredBy", "urn:habitat", "urn:environmentalMedium",
                    "urn:island", "urn:locality", "urn:maximumDepthInMeters", "urn:maximumDistanceAboveSurfaceInMeters", 
                    "urn:coordinateUncertaintyInMeters", "urn:microHabitat", "urn:minimumDepthInMeters",
                    "urn:minimumDistanceAboveSurfaceInMeters", "urn:monthCollected", "urn:permitInformation",
                    "urn:eventRemarks", "urn:stateProvince", "urn:taxTeam", "urn:yearCollected",
                    "urn:fixative", "urn:sampleOwnerInstitutionCode", "urn:collectionCode", "urn:preparations",
                    "urn:preservative", "urn:relaxant", "urn:license", "urn:EnteredBy", "urn:catalogNumber",
                    "urn:boldBIN", "urn:fieldNumber", "urn:genbankSpecimenVoucher", "urn:otherCatalogNumbers",
                    "urn:materialSampleID", "urn:occurrenceID", "urn:subProject", "urn:subSubProject",
                    "urn:boldProcessID", "urn:voucherURI", "urn:establishmentMeans", "urn:vernacularName",
                    "urn:dayIdentified", "urn:basisOfRecord", "urn:family", "urn:genus", "urn:identifiedBy",
                    "urn:infraClass", "urn:infraOrder", "urn:kingdom", "urn:lifeStage", "urn:taxonRank",
                    "urn:order", "urn:phylum", "urn:scientificName", "urn:sex", "urn:species", "urn:subclass",
                    "urn:subfamily", "urn:subGenus", "urn:suborder", "urn:subphylum", "urn:subSpecies",
                    "urn:subTribe", "urn:superClass", "urn:superFamily", "urn:superOrder", "urn:tribe",
                    "urn:wormsID", "urn:yearIdentified", "urn:tissueID", "urn:geneticTissueType",
                    "urn:plateID", "urn:wellID", "urn:tissueInstitution", "urn:tissueOtherCatalogNumbers",
                    "urn:tissuePreservative", "urn:associatedSequences", "urn:biosampleAccession"};
```

The detail view now takes 2 or 3 seconds to populate, down from 6 or  7 seconds.  We can make the detail view even faster by further constraining the list of fields coming from GEOME if desired.  

Another approach is to dig into optimizing the code for rendering the detail view. However, after examining the code-base in the LIMS to see if this was feasible, I discovered any fixes would require digging fairly deep into the logic for working with data structures as a whole and implementing changes could have possible unintended consequences.
