### ISSUE TITLE
BOLD export data crashes

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#127]
To replicate this, 

1.  Biocode Plugin Dropdown -> download traces from LIMS
2.  Retrieve using annotated LIMS information
3. <img width="646" alt="Screen Shot 2022-10-26 at 12 46 49 PM" src="https://user-images.githubusercontent.com/1154501/198122257-9274da00-20ce-4bc0-9a08-337af0c634c4.png">
5.  will take a bit to download
6.  File -> Export -> Bold trace submission
7.  Specify location by browsing to a writeable directory on your local computer
8. Enter a submission name

The error happens after this step

Note that the error does not happen when one manually enters data (change step #2 above)

**Comment by steierj** [comment]
Here is an example of a BOLD trace export that works when "Retrieve using annotated LIMS information" is selected:

1. search for "FY18_SuriFish_P12_Seq01_F" sequences in Biocode. 
2. Highlight the sequences, Biocode Plugin Dropdown -> download traces from LIMS to designated local Geneious directory
3. Highlight traces in local directory, File-> export -> BOLD trace submission
4. window should look the same as "#2" in the above comment 
5. once "OK" is clicked on the "BOLD trace submission" window, a "Rename" will pop up asking about standardizing BOLD primer and marker names. 
![Screen Shot 2022-10-26 at 5 48 23 PM](https://user-images.githubusercontent.com/74207845/198144924-317ba724-f5e8-4137-8eb4-86f3dff70c0f.png)
6. "Ok" this window and the export of traces should be completed successfully.

**Comment by jdeck88** [comment]
The ones that fails have no forward or reverse PCR primers in the LIMS.  They do, however, have a sequencing primer.  I can get this to work in one of two ways....
1) ignoring the null forward or/ reverse pcr primer submissions and only inserting the sequencing primer for the output.  
2) or, requring the forward / reverse pcr primer and outputting a message saying to fix this in the LIMS.. (instead of just failing!)

I do not know which of the above options is preferable to you.  I did just check the BOLD site (see https://v3.boldsystems.org/index.php/resources/handbook?chapter=3_submissions.html&section=trace_submissions) and it appears that forward and reverse primers ARE a minimal required field, so perhaps option #2 above.

**Comment by steierj** [comment]
Thank you for solving this!

**Comment by jdeck88** [comment]
@steierj I'll wait to release this feature in the next plugin release... Until then, your solution is to ensure you have forward and reverse primers coded into the LIMS to avoid this error message.

**Comment by jdeck88** [comment]
this is fixed... waiting for next plugin release
