### ISSUE TITLE
Add def for Reaction Status labels

### ISSUE THREAD

**Issue by steierj** [biocodellc/biocode-lims#128]
Add definitions to “pass” “tentative” and “fail” in the Geneious Biocode LIMS dropdown that pop up when the option is hovered on. Are there definitions existing somewhere already? In our own SIBN protocols, we have them listed as: 

Pass: Sequence has been checked for both quality and taxonomic accuracy and is ready for submission to public databases such as GenBank.

Tentative: Sequence has been checked only for quality - taxonomy is still under scrutiny.

Fail: Sequence has been checked for either quality and failed to meet barcode data standards, or for taxonomic accuracy and is a contaminent. It will not be pushed to public databases.

**Comment by jdeck88** [comment]
This has been added to code in latest commit.
