### ISSUE TITLE
Explore LIMS function outside of Geneious Environment

### ISSUE THREAD

**Issue by cbird808** [biocodellc/biocode-lims#129]
Hi John,

Just wondering if there are any plans to divorce this from geneious?

Cheers,

Chris

**Comment by jdeck88** [comment]
What functions do you want available outside of Geneious?  There are alot of features built into Geneious currently such as storing trace images, annotations, and tools for export to BOLD, workflows and alignments... this information would be hard to replicate and alot is dependent on the core Geneious environment.  However, there may be features and data which may be pushed to GEOME with the option of attaching sequence metadata later for users not working in the Geneious environment... could you provide a list here?

**Comment by jdeck88** [comment]
I don't think this issue is in scope with this particular issue-tracker which is implicitly about a Geneious LIMS... closing.
