### ISSUE TITLE
LIMS Query Slow

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#134]
Performing a basic search query is reported as slow.  for example, a basic query for "FY18_SuriFish_P12", select Plates checkbox.

**Comment by jdeck88** [comment]
Basic Queries are slow since it looks for FY18_SuriFish_P12 anywhere in the string of characters in the query in multiple places... i was able to speed up this query 4x by select "More Options" then
Plate Name  "begins with" FY18_SuriFish_P12
This query is much more efficient since it only looks starting from the beginning of a string.  reccomend users use advanced search options to look in particular fields and use "begins with" or "ends with" or simply "equals" for all queries.

**Comment by jdeck88** [comment]
I spent time looking at some other ways in which to speed up queries to GEOME.  The initial query first looks to LIMS database, e.g. LIMS Plate like contains flmnh_270   ... the query itself is composed of two parts: 1) a query to LIMS system to retrieve that plate name that is stored in the LIMS mysql database, which returns a list of tissue IDs, and then 2) a query to GEOME with unique tissueIDs.  The GEOME query is the part where the message says "Downloading....".  This is the SLOW part.  If i take a sample GEOME query, e.g. the following query:

```
curl -v -X POST \
  'https://api.geome-db.org/records/Tissue/json?page=0&limit=1000&includeEmptyProperties=false' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --compressed \
  --output response.json \
  -w '\nTotal time: %{time_total} seconds\n' \
  -d 'query=tissueID%3A%3A%22BOMAN_11085.1%22+OR+tissueID%3A%3A%22BOMAN_11068.1%22+OR+tissueID%3A%3A%22BOMAN_11093.1%22+OR+tissueID%3A%3A%22BOMAN_11114.1%22+OR+tissueID%3A%3A%22BOMAN_10997.1%22+OR+tissueID%3A%3A%22BOMAN_11105.1%22+OR+tissueID%3A%3A%22BOMAN_11094.1%22+OR+tissueID%3A%3A%22BOMAN_11034.1%22+OR+tissueID%3A%3A%22BOMAN_11051.1%22+OR+tissueID%3A%3A%22BOMAN_11018.1%22+OR+tissueID%3A%3A%22BOMAN_11092.1%22+OR+tissueID%3A%3A%22BOMAN_11107.1%22+OR+tissueID%3A%3A%22BOMAN_11115.1%22+OR+tissueID%3A%3A%22BOMAN_11000.1%22+OR+tissueID%3A%3A%22BOMAN_10998.1%22+OR+tissueID%3A%3A%22BOMAN_11052.1%22+OR+tissueID%3A%3A%22BOMAN_11095.1%22+OR+tissueID%3A%3A%22BOMAN_11009.1%22+OR+tissueID%3A%3A%22BOMAN_11026.1%22+OR+tissueID%3A%3A%22BOMAN_11091.1%22+OR+tissueID%3A%3A%22BOMAN_11006.1%22+OR+tissueID%3A%3A%22BOMAN_11079.1%22+OR+tissueID%3A%3A%22BOMAN_11049.1%22+OR+tissueID%3A%3A%22BOMAN_11096.1%22+OR+tissueID%3A%3A%22BOMAN_11019.1%22+OR+tissueID%3A%3A%22BOMAN_11083.1%22+OR+tissueID%3A%3A%22BOMAN_11053.1%22+OR+tissueID%3A%3A%22BOMAN_11023.1%22+OR+tissueID%3A%3A%22BOMAN_11060.1%22+OR+tissueID%3A%3A%22BOMAN_11116.1%22+OR+tissueID%3A%3A%22BOMAN_11090.1%22+OR+tissueID%3A%3A%22BOMAN_11103.1%22+OR+tissueID%3A%3A%22BOMAN_11010.1%22+OR+tissueID%3A%3A%22BOMAN_11067.1%22+OR+tissueID%3A%3A%22BOMAN_10996.1%22+OR+tissueID%3A%3A%22BOMAN_11097.1%22+OR+tissueID%3A%3A%22BOMAN_11117.1%22+OR+tissueID%3A%3A%22BOMAN_11041.1%22+OR+tissueID%3A%3A%22BOMAN_11011.1%22+OR+tissueID%3A%3A%22BOMAN_11037.1%22+OR+tissueID%3A%3A%22BOMAN_11024.1%22+OR+tissueID%3A%3A%22BOMAN_11104.1%22+OR+tissueID%3A%3A%22BOMAN_11055.1%22+OR+tissueID%3A%3A%22BOMAN_11080.1%22+OR+tissueID%3A%3A%22BOMAN_11020.1%22+OR+tissueID%3A%3A%22BOMAN_11098.1%22+OR+tissueID%3A%3A%22BOMAN_11004.1%22+OR+tissueID%3A%3A%22BOMAN_11003.1%22+OR+tissueID%3A%3A%22BOMAN_11071.1%22+OR+tissueID%3A%3A%22BOMAN_11021.1%22+OR+tissueID%3A%3A%22BOMAN_10992.1%22+OR+tissueID%3A%3A%22BOMAN_11101.1%22+OR+tissueID%3A%3A%22BOMAN_11064.1%22+OR+tissueID%3A%3A%22BOMAN_11118.1%22+OR+tissueID%3A%3A%22BOMAN_11102.1%22+OR+tissueID%3A%3A%22BOMAN_11013.1%22+OR+tissueID%3A%3A%22BOMAN_11048.1%22+OR+tissueID%3A%3A%22BOMAN_11073.1%22+OR+tissueID%3A%3A%22BOMAN_11099.1%22+OR+tissueID%3A%3A%22BOMAN_11110.1%22+OR+tissueID%3A%3A%22BOMAN_10985.1%22+OR+tissueID%3A%3A%22BOMAN_11070.1%22+OR+tissueID%3A%3A%22BOMAN_11005.1%22+OR+tissueID%3A%3A%22BOMAN_11039.1%22+OR+tissueID%3A%3A%22BOMAN_11022.1%22+OR+tissueID%3A%3A%22BOMAN_10993.1%22+OR+tissueID%3A%3A%22BOMAN_11065.1%22+OR+tissueID%3A%3A%22BOMAN_11119.1%22+OR+tissueID%3A%3A%22BOMAN_11001.1%22+OR+tissueID%3A%3A%22BOMAN_11074.1%22+OR+tissueID%3A%3A%22BOMAN_11108.1%22+OR+tissueID%3A%3A%22BOMAN_11087.1%22+OR+tissueID%3A%3A%22BOMAN_10986.1%22+OR+tissueID%3A%3A%22BOMAN_11082.1%22+OR+tissueID%3A%3A%22BOMAN_10999.1%22+OR+tissueID%3A%3A%22BOMAN_11088.1%22+OR+tissueID%3A%3A%22BOMAN_11075.1%22+OR+tissueID%3A%3A%22BOMAN_11062.1%22+OR+tissueID%3A%3A%22BOMAN_10990.1%22+OR+tissueID%3A%3A%22BOMAN_10991.1%22+OR+tissueID%3A%3A%22BOMAN_11113.1%22+OR+tissueID%3A%3A%22BOMAN_11059.1%22+OR+tissueID%3A%3A%22BOMAN_11109.1%22+OR+tissueID%3A%3A%22BOMAN_11002.1%22+OR+tissueID%3A%3A%22BOMAN_11032.1%22+OR+tissueID%3A%3A%22BOMAN_11081.1%22+OR+tissueID%3A%3A%22BOMAN_11045.1%22+OR+tissueID%3A%3A%22BOMAN_10987.1%22+OR+tissueID%3A%3A%22BOMAN_11015.1%22+OR+tissueID%3A%3A%22BOMAN_11076.1%22+OR+tissueID%3A%3A%22BOMAN_11028.1%22+OR+tissueID%3A%3A%22BOMAN_11033.1%22+OR+tissueID%3A%3A%22BOMAN_11089.1%22+OR+tissueID%3A%3A%22BOMAN_11063.1%22+_select_%3A%5BTissue%2CSample%2CEvent%5D&entity=Tissue'
```

runs in Curl in about 14 seconds.  Running through the Biocode plugin it takes about 35 seconds.  I did some research on Headers that were sent to the server and one area that holds promise is setting the Content-Length appropriately.  Strangely curl sent content-length is about 10 times larger than the java/biocode content-length header.  Unfortunately the Invocation.Builder that puts the query together in java does not let us to manually set the content-length header.   The spot where things are really slow is at https://github.com/biocodellc/biocode-lims/blob/de38ab1311f99038a1436d66766a4313c06f4a6f/src/com/biomatters/plugins/biocode/labbench/fims/geome/geomeFIMSConnection.java#L538   There could be other issues as well.  This research was taking me quite a bit of time so i stopped working on this and instead leaving this message about my progress and hopefully help in diagnosing at some future date.

**Comment by steierj** [comment]
Testing query speed as of 1.22.24 prior to update to new SI LIMS server:

Completion of Basic Query for "FY18_SuriFish_P12" took 110 seconds.
Completion of Advanced Query (specifying "Plate name(LIMS)" and "Begins with") for "FY18_SuriFish_P12" took 8 seconds. 

Will test this again after LIMS server is updated to see if there are improvement of speeds.

**Comment by steierj** [comment]
with updated LIMS server, as of 1.27.24

Completion of Basic Query for "FY18_SuriFish_P12" took 100 seconds.
Completion of Advanced Query (specifying "Plate name(LIMS)" and "Begins with") for "FY18_SuriFish_P12" took 21 seconds.


Advanced query actually took longer!

It does not appear that the new server made improvements in query speed.

**Comment by steierj** [comment]
In new Biocode 3.0.22 release (Oct 21,2024), significant speed increases seen in basic searches: 
Completion of Basic Query for "FY18_SuriFish_P12" took 55 seconds.
Completion of Advanced Query (specifying "Plate name(LIMS)" and "Begins with") for "FY18_SuriFish_P12" took 20 seconds.

**Comment by jdeck88** [comment]
Marking this as complete with latest commit 7013e032c106e437c2c3d5041dc455693ebbe181 and release 3.0.22
