### ISSUE TITLE
Mark as Pass function lagging

### ISSUE THREAD

**Issue by steierj** [biocodellc/biocode-lims#135]
This does not involve intricate steps to recreate, you just need a contig or consensus sequence loaded onto your local Geneious, log onto the biocode lims, return to the local document, 
biocode dropdown -> mark as pass in LIMS -> function will take ~30 seconds to complete function just on a single sequence document.

**Comment by jdeck88** [comment]
Julia, can you try the latest version of plugin v3.0.18--- if you install this plugin and re-try, the changes i've made in that plugin *might* improve the performance here...

**Comment by jdeck88** [comment]
@steierj  indicates performance is improved here also as a result of changes in 3.0.18 so marking as closed.
