### ISSUE TITLE
Show marked as tentative in the plate viewer

### ISSUE THREAD

**Issue by OMahoneyM** [biocodellc/biocode-lims#136]
When a sequence is marked as passed or failed, it's noted in the cycle sequencing plate data and the well color will change to green or red, respectively. Currently, when a sequence is marked as tentative, it isn't recorded in the corresponding cycle sequencing plates. The Reaction State instead shows not run and the well is left white in the viewer. I propose that the the _suspect_ option of Reaction State picklist be co-opted for this and changed to _tentative_ for cycle sequencing plates only (It's still a useful option for PCR plates). It can then use _suspect's_ assigned the yellow/orange color to denote wells marked as tentative.

**Comment by jdeck88** [comment]
I will need to schedule a time to go over this operation with someone...
@tweeds volunteers to help me with this

**Comment by tweedts** [comment]
Reviewed with John. 
Colors on the cycle sequencing plate viewer are assigned via reaction status in the workflow metadata. E.g. when sequences are marked as passed, the reaction state of a well of the cycle sequencing plate is changed to passed and the well is color-coded green. Likewise for failed.
There is currently no change in workflow reaction state and corresponding plate color when sequences are marked as tentative. But reaction state 'suspect' does not equate to a 'tentative' sequence status (one implies uncertainty in reaction success, the other a sequence needing final review). 
Suggest tabling issue for now.

**Comment by jdeck88** [comment]
Solved with issue #144
