### ISSUE TITLE
Allow custom date formats in plate documents

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#43]
<p>Because the default is quite verbose and the plate view could be more compact if the user could choose a shorter format more suited to their needs</p>

<p>The interface should be a dialog with a text field for entering a standard java date format (with a link to documentation), plus a dropdown to let users choose common ones (selecting form the dropdown fills in the textfield).  We can also have a sample date label to show what their format looks like.</p>
<i>[MBP-297] created by steve</i>

**Comment by chrispmeyer** [comment]
we can look into this - assign to John Deck

**Comment by jdeck88** [comment]
shelving this
