### ISSUE TITLE
Display the number of failed reactions as a field on plates

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#62]
<p>from the requester: john.s.wood@colorado.edu or jwood@pisces-molecular.com</p>

<p>Similar to most labs, we not infrequently have one or more samples fail from a batch, necessitating going back and repeating the reaction and/or sequencing runs for these samples. While having the red & green colors for cells in a plate are good for seeing exactly which samples failed, we have to open the plate to see these. Is there any global way to record & see these stragglers (i. e. “plate x = two failed samples, plate y = no failures, plate z = one failed sample, etc.)? (perhaps some sort of “task manager” akin to what Microsoft Outlook has?)</p>

<i>[MBP-303] created by steve</i>

**Comment by chrispmeyer** [comment]
Could use the Tabular Plate View to quickly see which ones failed - sort on reaction status
