### ISSUE TITLE
There should be a way to find out where an extraction has been moved to

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#63]
<p>Once an extraction has been moved to another plate there is no way to track it from the original plate.  This is quite problematic for a multi-user environment.  </p>

<p>A simple note like "Moved to Plate_name.well_number would work.  But we would have to see if it is possible with the current data structures and schema.</p>

<p>From a user at the Smithsonian NMNH:</p>

<p>One other thing that I think we’ve discussed before and goes along with the “current extraction plate” problem. If I have an original extraction plate that has been cherry picked basically impossible from within the LIMS to tell where those samples currently are.</p>

<p>For example, if I search PBALI_046 I see that only an extraction plate exists, but that extraction plate has no info attached because all of the samples have been moved elsewhere, but there is no easy way to tell where those tubes went without already having that information. </p>

<p>Case in point, when Allen made a new extraction plate for the samples he wanted to send to CA for NGS work. Those specimens disappeared off of extraction plates I was still actively working on (making new PCRs from my existing working stock DNA plate with all 94 samples on it) and so I had to do some backtracking to figure out exactly which samples were missing to track down where they went so I could at include the metadata on my new PCR plates. That might be a complicated and one-off example, but it’s one that did happen.</p>
<i>[MBP-686] created by matthew</i>

**Comment by chrispmeyer** [comment]
this has been dealt with by not moving DNA barcodes when cloning the plate
