### ISSUE TITLE
Users should be able to specify their own species field

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#65]
<p>When annotating LIMS data we put species and everything below it into the organism field.  The rest goes into the taxonomy field.</p>

<p>However we determine the species as the first field that contains the string "speci".  This works in most cases.  However there are other languages out there.  For example in German it might be spezies.  So ideally the user would be able to select it themselves.</p>
<i>[MBP-641] created by matthew</i>

**Comment by chrispmeyer** [comment]
this seems to be working - is also a Geneious issue, not LIMS plug-in?
