### ISSUE TITLE
More effective and efficient binning parameters for assemblies

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#74]
<p>Now that we have some better consensus algorithms in place we can probably simplify the binning parameters for assemblies. Should be done in collaboration with chris since he has set up all the binning params for biocode.</p>

<ul>
	<li># Disagreements is irrelevant because they are normally resolved by pairwise assembly.</li>
	<li>Min % of reference length is redundant because of the min length.</li>
	<li>Probably need a max ambiguities field since the consensus algorithm will call ambiguities in nasty cases (if two opposing calls are of similar quality). Should default to 0 for high bin.</li>
</ul>

<i>[MBP-116] created by richard</i>

**Comment by chrispmeyer** [comment]
most import aspect was to add Max Ambiguities - which is done!
