### ISSUE TITLE
Translate: Should have "relative to" option like the sequence view

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#75]
<p>Currently you can't get the translations out of an alignment which is using "relative to" alignment or consensus. It would be cool to have this option in the extract translation action. It would need to throw away certain amino acids though... it should definitely use the same code as the sequence view if we do this.</p>

<p>Requested by Sylvain of course.</p>
<i>[MBP-90] created by richard</i>

**Comment by chrispmeyer** [comment]
this is a Geneious issue, not a Biocode LIMS issue.
